CREATE OR REPLACE FUNCTION 
	criar_professores()
RETURNS VOID AS $$

BEGIN
  -- Adição dos professores  
  INSERT INTO PROFESSOR (NOME, DEPARTAMENTO_ID) VALUES
    ('ANA KARINE PEREIRA', 1),
    ('CRISTIANE GOMES BARRETO', 1),
    ('DORIS ALEIDA VILLAMIZAR SAYAGO', 2),
    ('FREDERIC ADELIN GEORGES MERTENS', 2),
    ('JESSICA PEREIRA GARCIA', 3),
    ('JONATHAS FELIPE AIRES FERREIRA', 3),
    ('LAURA ANGELICA FERREIRA DARNET', 4),
    ('MAURO GUILHERME MAIDANA CAPPELLARO', 4);

END;
$$ LANGUAGE plpgsql;