BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS ESTUDANTE (
    ID SERIAL NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    MATRICULA VARCHAR(10) NOT NULL,
    SENHA VARCHAR(60) NOT NULL,
    ADM BOOLEAN DEFAULT FALSE,

    CONSTRAINT PK_ESTUDANTE PRIMARY KEY (ID),
    CONSTRAINT UQ_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTO (
    ID SERIAL NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    DESCRICAO VARCHAR(4500),
    
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DISCIPLINA (
    ID SERIAL NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    DEPARTAMENTO_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_DISCIPLINA PRIMARY KEY (ID),
    CONSTRAINT UQ_NOME UNIQUE (NOME),
    CONSTRAINT FK_DISCIPLINA_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO (ID)
);

CREATE TABLE IF NOT EXISTS PROFESSOR (
    ID SERIAL NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    DEPARTAMENTO_ID INTEGER NOT NULL,
    FOTO BYTEA, 
    
    CONSTRAINT PK_PROFESSOR PRIMARY KEY (ID),
    CONSTRAINT FK_PROFESSOR_DEPARTAMENTO FOREIGN KEY (DEPARTAMENTO_ID) REFERENCES DEPARTAMENTO (ID)
);

CREATE TABLE IF NOT EXISTS TURMA (
    PROFESSOR_ID INTEGER NOT NULL,
    DISCIPLINA_ID INTEGER NOT NULL,
    ANO INTEGER NOT NULL,
    SEMESTRE INTEGER NOT NULL,
    CODIGO VARCHAR(6) NOT NULL,
    
    CONSTRAINT PK_TURMA PRIMARY KEY (PROFESSOR_ID, DISCIPLINA_ID, ANO, SEMESTRE, CODIGO),
    CONSTRAINT FK_TURMA_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (ID),
    CONSTRAINT FK_TURMA_DISCIPLINA FOREIGN KEY (DISCIPLINA_ID) REFERENCES DISCIPLINA (ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO_PROFESSOR (
    ID SERIAL NOT NULL,
    TEXTO VARCHAR(9000) NOT NULL,
    LIKES INTEGER NOT NULL DEFAULT 0,
    DISLIKES INTEGER NOT NULL DEFAULT 0,
    DENUNCIAS INTEGER NOT NULL DEFAULT 0,
    ESTUDANTE_ID INTEGER NOT NULL,
    PROFESSOR_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_AVALIACAO_PROFESSOR PRIMARY KEY (ID),
    CONSTRAINT FK_AVALIACAO_PROFESSOR_ESTUDANTE FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE (ID),
    CONSTRAINT FK_AVALIACAO_PROFESSOR_PROFESSOR FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (ID)
);

CREATE TABLE IF NOT EXISTS AVALIACAO_TURMA (
    ID SERIAL NOT NULL,
    TEXTO VARCHAR(9000) NOT NULL,
    LIKES INTEGER NOT NULL DEFAULT 0,
    DISLIKES INTEGER NOT NULL DEFAULT 0,
    DENUNCIAS INTEGER NOT NULL DEFAULT 0,
    ESTUDANTE_ID INTEGER NOT NULL,
    TURMA_PROFESSOR_ID INTEGER NOT NULL,
    TURMA_DISCIPLINA_ID INTEGER NOT NULL,
    TURMA_ANO INTEGER NOT NULL,
    TURMA_SEMESTRE INTEGER NOT NULL,
    TURMA_CODIGO VARCHAR(6) NOT NULL,
    
    CONSTRAINT PK_AVALIACAO_TURMA PRIMARY KEY (ID),
    CONSTRAINT FK_AVALIACAO_PROFESSOR_ESTUDANTE FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE (ID),
    CONSTRAINT FK_AVALIACAO_TURMA_DISCIPLINA FOREIGN KEY (TURMA_PROFESSOR_ID, TURMA_DISCIPLINA_ID, TURMA_ANO, TURMA_SEMESTRE, TURMA_CODIGO) REFERENCES TURMA (PROFESSOR_ID, DISCIPLINA_ID, ANO, SEMESTRE, CODIGO)
);

CREATE TABLE IF NOT EXISTS DENUNCIA_AVALIACAO_PROFESSOR (
    ID SERIAL NOT NULL,
    
    AVALIACAO_PROFESSOR_ID INTEGER NOT NULL,
    ESTUDANTE_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_DENUNCIA_AVALIACAO_PROFESSOR PRIMARY KEY (ID),
    CONSTRAINT FK_DENUNCIA_AVALIACAO_PROFESSOR FOREIGN KEY (AVALIACAO_PROFESSOR_ID) REFERENCES AVALIACAO_PROFESSOR (ID),
    CONSTRAINT FK_DENUNCIA_ESTUDANTE FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE (ID)
);

CREATE TABLE IF NOT EXISTS DENUNCIA_AVALIACAO_TURMA (
    ID SERIAL NOT NULL,
    
    AVALIACAO_TURMA_ID INTEGER NOT NULL,
    ESTUDANTE_ID INTEGER NOT NULL,
    
    CONSTRAINT PK_DENUNCIA_AVALIACAO_TURMA PRIMARY KEY (ID),
    CONSTRAINT FK_DENUNCIA_AVALIACAO_TURMA FOREIGN KEY (AVALIACAO_TURMA_ID) REFERENCES AVALIACAO_TURMA (ID),
    CONSTRAINT FK_AVALIACAO_PROFESSOR_PROFESSOR FOREIGN KEY (ESTUDANTE_ID) REFERENCES ESTUDANTE (ID)
);



COMMIT;